version: '3.8'

services:
  db:
    image: postgres:15.6-alpine3.18
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=$(DB_HOST)
    ports:
      - "5433:5433"
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    command: uvicorn src.main:app --host 0.0.0.0 --port 8001 --proxy-headers --reload
    depends_on:
      - db
