version: '3.8'

services:
  db:
    image: postgres:15.6-alpine3.18
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5433:5433"
    volumes:
      - ./data/db:/var/lib/postgresql/data